package edu.psu.ist440.group2.workflowupdateservice;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * JobItem is a POJO class that contains all of the data associated with a
 * decryption job via Amazon's DynamoDBMapper API.
 * 
 * @see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html
 * 
 * @author j6r
 *
 */
@DynamoDBTable(tableName = "Jobs")
public class JobItem {
	
	/** set by the previous task during exception handling */
	private boolean failed;

	/** ID of the user who uploaded the photo */
	private String userId;

	/** Job/execution ID */
	private String jobId;

	/** Timestamp when the photo was uplaoded */
	private String createdDate;

	/**
	 * Current state of the job
	 * 
	 * Values are provided and specified by the workflow
	 */
	private String status;

	/** Data for the uploaded image file */
	private UploadedImageInfo uploadedImageInfo;

	/** Data for the file produced by the OCR module */
	private OCRInfo ocrInfo;

	/** Data for the files produced by the decryption and translation modules */
	private List<DecryptedInfo> decryptedInfo;

	public JobItem() {
		uploadedImageInfo = new UploadedImageInfo();
		ocrInfo = new OCRInfo();
		decryptedInfo = new ArrayList<>();
	}
		
	
	@DynamoDBIgnore
	public boolean isFailed() {
		boolean decryptionFailure = false;
		for (DecryptedInfo di : decryptedInfo) {
			if (di.failed) {
				decryptionFailure = true;
				break;
			}
		}
		
		return (this.failed || ocrInfo.failed || decryptionFailure);
	}

	public void setFailed(boolean failed) {
		this.failed = failed;
	}

	@DynamoDBHashKey(attributeName = "userId")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBRangeKey(attributeName = "jobId")
	@DynamoDBAutoGeneratedKey
	public String getJobId() {
		return jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@DynamoDBAttribute(attributeName = "createdDate")
	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@DynamoDBAttribute(attributeName = "status")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@DynamoDBAttribute(attributeName = "uploadedImageInfo")
	public UploadedImageInfo getUploadedImageInfo() {
		return uploadedImageInfo;
	}

	public void setUploadedImageInfo(UploadedImageInfo uploadedImageInfo) {
		this.uploadedImageInfo = uploadedImageInfo;
	}

	@DynamoDBAttribute(attributeName = "OCRInfo")
	public OCRInfo getOcrInfo() {
		return ocrInfo;
	}

	public void setOcrInfo(OCRInfo ocrInfo) {
		this.ocrInfo = ocrInfo;
	}

	@DynamoDBAttribute(attributeName = "decryptedInfo")
	public List<DecryptedInfo> getDecryptedInfo() {
		return decryptedInfo;
	}

	public void setDecryptedInfo(List<DecryptedInfo> decryptedInfo) {
		this.decryptedInfo = decryptedInfo;
	}

	@DynamoDBDocument
	public static class UploadedImageInfo {
		
		/** S3 bucket where the file is stored */
		private String bucket = "";

		/** S3 key (file name) */
		private String key = "";

		@DynamoDBAttribute(attributeName = "bucket")
		public String getBucket() {
			return bucket;
		}

		public void setBucket(String imageBucket) {
			this.bucket = imageBucket;
		}

		@DynamoDBAttribute(attributeName = "key")
		public String getKey() {
			return key;
		}

		public void setKey(String imageKey) {
			this.key = imageKey;
		}

	}

	@DynamoDBDocument
	public static class OCRInfo {
		
		/** set by the OCR task during exception handling */
		private boolean failed;
		
		/** S3 bucket where the file is stored */
		private String bucket;
		
		/** S3 key (file name) */
		private String key;

		@DynamoDBAttribute(attributeName = "bucket")
		public String getBucket() {
			return bucket;
		}

		public void setBucket(String imageBucket) {
			this.bucket = imageBucket;
		}

		@DynamoDBAttribute(attributeName = "key")
		public String getKey() {
			return key;
		}

		public void setKey(String imageKey) {
			this.key = imageKey;
		}

		@DynamoDBIgnore
		public boolean isFailed() {
			return failed;
		}

		public void setFailed(boolean failed) {
			this.failed = failed;
		}
		
		

	}

	@DynamoDBDocument
	public static class DecryptedInfo {
		/** set by the decryption task during exception handling */
		private boolean failed;
		
		/** Name of the method used to decrypt the file (eg Caesar) */
		private String method;
		
		/** Optional confidence value from the decryption algrorithm */
		private String confidence;
		
		/** Language used for decryption */
		private String sourceLanguage;
		
		/** S3 bucket containing the output of the decryption module */
		private String decryptedBucket;
		
		/** S3 key (file name) for the output of the decryption module */
		private String decryptedKey;
		
		/** S3 bucket containing the output of the translation module */
		private String translatedBucket;
		
		/** S3 key (file name) for the output of the translation module */
		private String translatedKey;
		
		@DynamoDBIgnore
		public boolean isFailed() {
			return failed;
		}

		public void setFailed(boolean failed) {
			this.failed = failed;
		}

		@DynamoDBAttribute(attributeName = "method")
		public String getMethod() {
			return method;
		}

		public void setMethod(String method) {
			this.method = method;
		}

		@DynamoDBAttribute(attributeName = "confidence")
		public String getConfidence() {
			return confidence;
		}

		public void setConfidence(String confidence) {
			this.confidence = confidence;
		}

		@DynamoDBAttribute(attributeName = "sourceLanguage")
		public String getSourceLanguage() {
			return sourceLanguage;
		}

		public void setSourceLanguage(String language) {
			this.sourceLanguage = language;
		}

		@DynamoDBAttribute(attributeName = "decryptedBucket")
		public String getDecryptedBucket() {
			return decryptedBucket;
		}

		public void setDecryptedBucket(String decryptedBucket) {
			this.decryptedBucket = decryptedBucket;
		}

		@DynamoDBAttribute(attributeName = "decryptedKey")
		public String getDecryptedKey() {
			return decryptedKey;
		}

		public void setDecryptedKey(String decryptedKey) {
			this.decryptedKey = decryptedKey;
		}

		@DynamoDBAttribute(attributeName = "translatedBucket")
		public String getTranslatedBucket() {
			return translatedBucket;
		}

		public void setTranslatedBucket(String translatedBucket) {
			this.translatedBucket = translatedBucket;
		}

		@DynamoDBAttribute(attributeName = "translatedKey")
		public String getTranslatedKey() {
			return translatedKey;
		}

		public void setTranslatedKey(String translatedKey) {
			this.translatedKey = translatedKey;
		}

	}

}
