package edu.psu.ist440.group2.mappings;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Jobs")
public class JobItem {

	private String userId;
	private String jobId;
	private String createdDate;
	private String status;
	private UploadedImageInfo uploadedImageInfo;
	private OCRInfo ocrInfo;
	private List<DecryptedInfo> decryptedInfo;
	
	public JobItem() {
		uploadedImageInfo = new UploadedImageInfo();
		ocrInfo = new OCRInfo();
		decryptedInfo = new ArrayList<>();
	}

	@DynamoDBHashKey(attributeName = "userId")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBRangeKey(attributeName = "jobId")
	@DynamoDBAutoGeneratedKey
	public String getJobId() {
		return jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@DynamoDBAttribute(attributeName = "createdDate")
	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@DynamoDBAttribute(attributeName = "status")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@DynamoDBAttribute(attributeName = "uploadedImageInfo")
	public UploadedImageInfo getUploadedImageInfo() {
		return uploadedImageInfo;
	}

	public void setUploadedImageInfo(UploadedImageInfo uploadedImageInfo) {
		this.uploadedImageInfo = uploadedImageInfo;
	}

	@DynamoDBAttribute(attributeName = "OCRInfo")
	public OCRInfo getOcrInfo() {
		return ocrInfo;
	}

	public void setOcrInfo(OCRInfo ocrInfo) {
		this.ocrInfo = ocrInfo;
	}

	@DynamoDBAttribute(attributeName = "decryptedInfo")
	public List<DecryptedInfo> getDecryptedInfo() {
		return decryptedInfo;
	}

	public void setDecryptedInfo(List<DecryptedInfo> decryptedInfo) {
		this.decryptedInfo = decryptedInfo;
	}

	@DynamoDBDocument
	public static class UploadedImageInfo {
		private String bucket = "";
		private String key = "";
		
		@DynamoDBAttribute(attributeName = "bucket")
		public String getBucket() {
			return bucket;
		}

		public void setBucket(String imageBucket) {
			this.bucket = imageBucket;
		}

		@DynamoDBAttribute(attributeName = "key")
		public String getKey() {
			return key;
		}

		public void setKey(String imageKey) {
			this.key = imageKey;
		}

	}

	@DynamoDBDocument
	public static class OCRInfo {
		private String bucket;
		private String key;

		@DynamoDBAttribute(attributeName = "bucket")
		public String getBucket() {
			return bucket;
		}

		public void setBucket(String imageBucket) {
			this.bucket = imageBucket;
		}

		@DynamoDBAttribute(attributeName = "key")
		public String getKey() {
			return key;
		}

		public void setKey(String imageKey) {
			this.key = imageKey;
		}

	}

	@DynamoDBDocument
	public static class DecryptedInfo {
		private String method;
		private String confidence;
		private String language;
		private String decryptedBucket;
		private String decryptedKey;
		private String translatedBucket;
		private String translatedKey;

		@DynamoDBAttribute(attributeName = "method")
		public String getMethod() {
			return method;
		}

		public void setMethod(String method) {
			this.method = method;
		}

		@DynamoDBAttribute(attributeName = "confidence")
		public String getConfidence() {
			return confidence;
		}

		public void setConfidence(String confidence) {
			this.confidence = confidence;
		}

		@DynamoDBAttribute(attributeName = "sourceLanguage")
		public String getLanguage() {
			return language;
		}

		public void setLanguage(String language) {
			this.language = language;
		}

		@DynamoDBAttribute(attributeName = "decrypted_bucket")
		public String getDecryptedBucket() {
			return decryptedBucket;
		}

		public void setDecryptedBucket(String decryptedBucket) {
			this.decryptedBucket = decryptedBucket;
		}

		@DynamoDBAttribute(attributeName = "decrypted_key")
		public String getDecryptedKey() {
			return decryptedKey;
		}

		public void setDecryptedKey(String decryptedKey) {
			this.decryptedKey = decryptedKey;
		}

		@DynamoDBAttribute(attributeName = "translatedBucket")
		public String getTranslatedBucket() {
			return translatedBucket;
		}

		public void setTranslatedBucket(String translatedBucket) {
			this.translatedBucket = translatedBucket;
		}

		@DynamoDBAttribute(attributeName = "translatedKey")
		public String getTranslatedKey() {
			return translatedKey;
		}

		public void setTranslatedKey(String translatedKey) {
			this.translatedKey = translatedKey;
		}

	}

}
